name = "comments-api-worker"
main = "src/index.ts"
compatibility_date = "2026-05-03"
workers_dev = true

[vars]
ALLOWED_ORIGIN = "https://ximo.qzz.io"
ALLOWED_ADMIN_URL = "https://ximo.qzz.io/admin/comments/"
PUBLIC_SITE_URL = "https://ximo.qzz.io"
GITHUB_CLIENT_ID = "Ov23liJmx2avHxTk6QAQ"
GITHUB_OAUTH_REDIRECT_URI = "https://comments-api-worker.251873620.workers.dev/api/admin/callback"
ADMIN_GITHUB_USERS = "PWMPro-a"

[[d1_databases]]
binding = "DB"
database_name = "lin-notes-comments"
database_id = "7c5ec6cb-3203-4b86-9840-608cc183327d"
